config/routes.rb
Rails.application.routes.draw do
  # devise_forは最初に記述する（最後に記述するとshowにリダイレクトされる）
  devise_for :users
  root to: 'homes#top'
  #homes/about -> home/about
  resources :homes, only: [], path: 'home' do
    get 'about', on: :collection
  end

  # いいねとコメントはBookに対してされるためネスト
  resources :books, only:[:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  # 引数で渡されたユーザidがFavoritesテーブル内に存在するかどうか
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :user_id, scope: :book_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  # profile_imageという名前でActiveStorageでプロフィール画像を保存
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # プロファイル画像表示のメソッド
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインしていない状態でトップページ以外にアクセスされた場合は、ログイン画面へリダイレクト
  before_action :authenticate_user!, except: [:top, :about]
  # コントローラーアクション実行前に対象メソッﾄﾞを実行（パラメーターの許可）
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

   protected

  # ユーザー登録(sign_up)の際にユーザー名(name)とemailデータ操作を許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer || books_path
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer || books_path
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    raise ActiveRecord::RecordNotFound
  end

  def create
    #データを受け取り新規登録するためのインスタンス作成
    @new_book = Book.new(book_params)
    # ユーザーIDの紐付け
    @new_book.user_id = current_user.id
    if @new_book.save
      #各idのページにリダイレクト
      flash[:notice] = "You have created a book successfully." #フラッシュメッセージ
      redirect_to book_path(@new_book.id)
    else
      @books = Book.all #render用にbooksリスト表示のため(indexアクションは呼び出されない)
      render :index
    end
  end

  def index
    @books = Book.all
    @new_book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated a book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id]) # データ（レコード）を1件取得
    book.destroy # データ（レコード）を削除
    redirect_to books_path # 投稿一覧画面へリダイレクト
  end

   private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    #直前のページにリダイレクト（できない場合はindex）
    redirect_to request.referer || books_path
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer || books_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
 <!-- FontAwesomeの読み込み -->
<script src="https://kit.fontawesome.com/60ee8a5e8e.js" crossorigin="anonymous"></script>
<div class="col-md-3">
  <h2>User info</h2>
  <!--bookが存在しないとnot foundになるため、条件分岐-->
  <% if @book.present? %>
    <%= image_tag @book.user.get_profile_image(100,100) %>
  <% else %>
    <%= image_tag current_user.get_profile_image(100,100) %>
  <% end %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
    	  <th>name</th>
    	  <!--bookが存在しないとnot foundになるため条件分岐-->
    	  <th><%= @book.present? ? @book.user.name : current_user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th>
    	    <!--showとindexで別々のintroductionを表示するため-->
    	    <%= @book.present? && request.path == book_path(@book) ? @book.user.introduction : current_user.introduction %>
    	  </th>
    	</th>
    </tbody>
  </table>
  <div class="row">
    <!--showから自分以外のユーザーeditにアクセスする場合は自分のユーザーページにアクセスされる-->
    <% if request.path == books_path || (@book && @book.user == current_user) %>
      <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(@book.user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <!-- form_with部分 -->
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label for="book_body">Opinion</label>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <strong><h3><%= @book.errors.count %> <%= 'error'.pluralize(@book.errors.count) %> prohibited this book from being saved:</h3></strong>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>

        <%= link_to 'Show', book_path(@book.id) %>
        |
        <%= link_to 'Back', books_path %>

      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
 <!--containerでコンテンツをまとめて、rowで水平に配置-->
 <% if @new_book.errors.any? %>
  <strong><h3><%= @new_book.errors.count %> <%= 'error'.pluralize(@new_book.errors.count) %> prohibited this book from being saved:</h3></strong>
  <ul>
    <% @new_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'list', book: @new_book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table=hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <span class="text-danger">
                        <i class="fas fa-heart"></i>
                        <%= book.favorites.count %>
                      </span>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <span class="text-primary">
                        <i class="fas fa-heart"></i>
                        <%= book.favorites.count %>
                      </span>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td><p>コメント数：<%= book.book_comments.count %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--インスタンス変数名に注意-->
    <%= render 'list', book: @new_book %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table=hover table-inverse">
        <tbody>
            <tr>
              <td>
                <%= link_to image_tag(@book.user.get_profile_image(100,100)), user_path(@book.user.id) %>
                <br>
                <%= link_to @book.user.name, user_path(@book.user.id) %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
                <td><%= link_to 'Edit',edit_book_path(@book.id), class: "btn btn-sm btn-success edit_#{@book.id}" %></td>
                <!--ハッシュの表記に注意-->
                <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-sm btn-danger" %></td>
              <% end %>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <span class="text-danger">
                        <i class="fas fa-heart"></i>
                        <%= @book.favorites.count %>
                      </span>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <span class="text-primary">
                        <i class="fas fa-heart"></i>
                        <%= @book.favorites.count %>
                      </span>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td><p>コメント数：<%= @book.book_comments.count %></p></td>
            </tr>
        </tbody>
      </table>
      <div>
        <% @book.book_comments.each do |book_comment| %>
          <p>
            <%= image_tag book_comment.user.get_profile_image(100,100) %> <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
            <% end %>
          </p>
          <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
        <% end %>
      </div>
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5', class: "col-md-12" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<script src="https://kit.fontawesome.com/60ee8a5e8e.js" crossorigin="anonymous"></script>
<div class="container">
  <div class="row">
    <!--px-3(左右のx方向にpadding), mx-auto(左右マージン)-->
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<script src="https://kit.fontawesome.com/60ee8a5e8e.js" crossorigin="anonymous"></script>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <!--新しい行-->
        <div class="row">
          <!--mb-3で下側マージンを設定、btn-info(blue), btn-sm(button-size), btn-block(col-10 size)-->
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <!--新しい行-->
        <div class="row">
          <!--btn-sucess(green), btn-sm(button-size), btn-block(col-10 size)-->
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--Font Awesomeの設定-->
    <script src="https://kit.fontawesome.com/60ee8a5e8e.js" crossorigin="anonymous"></script>
    <title>Booker2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <!--ナビゲーションアイコンを開く前に隠す-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to current_user, class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_homes_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!--フラッシュメッセージ-->
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>">
        <%= msg %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      <% if @user.errors.any? %>
          <%= @user.errors.count %> <%= 'error'.pluralize(@user.errors.count) %> prohibited this book from being saved
          <ul>
              <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
          </ul>
      <% end %>

      <%= form_with model: @user do |f| %>

        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class: 'form-control' %>
        </div>

        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>

        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, id: "user_introduction", class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- FontAwesomeの読み込み -->
<script src="https://kit.fontawesome.com/60ee8a5e8e.js" crossorigin="anonymous"></script>
<% if @book.errors.any? %>
  <%= @book.errors.count %> <%= 'error'.pluralize(@book.errors.count) %> prohibited this book from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%= current_user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%= current_user.introduction %></th>
        	</th>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block edit_user_path" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
      <!-- form_with部分 -->
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table=hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag(user.get_profile_image(100,100)) %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- FontAwesomeの読み込み -->
<script src="https://kit.fontawesome.com/60ee8a5e8e.js" crossorigin="anonymous"></script>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%= @user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%= @user.introduction %></th>
        	</th>
        </tbody>
      </table>
      <div class="row">
        <%= link_to (@user == current_user) ? edit_user_path(current_user) : edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block edit_user_path" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <% if @book.errors.any? %>
          <%= @book.errors.count %> <%= 'error'.pluralize(@book.errors.count) %> prohibited this book from being saved
          <ul>
              <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
          </ul>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <!-- form_with部分 -->
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table=hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <span class="text-danger">
                        <i class="fas fa-heart"></i>
                        <%= book.favorites.count %>
                      </span>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <span class="text-primary">
                        <i class="fas fa-heart"></i>
                        <%= book.favorites.count %>
                      </span>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td><p>コメント数：<%= book.book_comments.count %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>